<a href="https://colab.research.google.com/github/snagine/PythonDSA/blob/main/Movielense.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
import numpy as np
import pandas as pd

movie = pd.read_csv("drive/MyDrive/GreatLearning/data/movie.csv")
print(movie.shape)
movie.head()
print(movie.info())

(1680, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   movie id      1680 non-null   int64 
 1   movie title   1680 non-null   object
 2   release date  1680 non-null   object
 3   Action        1680 non-null   int64 
 4   Adventure     1680 non-null   int64 
 5   Animation     1680 non-null   int64 
 6   Childrens     1680 non-null   int64 
 7   Comedy        1680 non-null   int64 
 8   Crime         1680 non-null   int64 
 9   Documentary   1680 non-null   int64 
 10  Drama         1680 non-null   int64 
 11  Fantasy       1680 non-null   int64 
 12  Film-Noir     1680 non-null   int64 
 13  Horror        1680 non-null   int64 
 14  Musical       1680 non-null   int64 
 15  Mystery       1680 non-null   int64 
 16  Romance       1680 non-null   int64 
 17  Sci-Fi        1680 non-null   int64 
 18  Thriller      1680 non-null   int64 


In [ ]:
movie.describe()
movie.columns

Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [ ]:
movie.head(10)
genres = ['Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western']
movie[genres].sum().sort_values(ascending=False)

movie['New-genre'] = movie.loc[:, genres].sum(axis=1)
movie.columns


Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western', 'New-genre'],
      dtype='object')

In [ ]:
movie[genres].sum().sort_values(ascending=False)

Drama          725
Comedy         505
Action         251
Thriller       251
Romance        247
Adventure      135
Childrens      122
Crime          109
Sci-Fi         101
Horror          92
War             71
Mystery         61
Musical         56
Documentary     50
Animation       42
Western         27
Film-Noir       24
Fantasy         22
dtype: int64

In [ ]:
movie.loc[:, genres].sum(axis=1)

0       3
1       3
2       1
3       3
4       3
       ..
1675    1
1676    2
1677    2
1678    1
1679    1
Length: 1680, dtype: int64

In [ ]:
movie.loc[:, ['Action','Adventure']].sum(axis=1)

0       0
1       2
2       0
3       1
4       0
       ..
1675    0
1676    0
1677    0
1678    0
1679    0
Length: 1680, dtype: int64

In [ ]:
movie.loc[:, ['Action','Adventure']]

Action  Adventure
0          0          0
1          1          1
2          0          0
3          1          0
4          0          0
...      ...        ...
1675       0          0
1676       0          0
1677       0          0
1678       0          0
1679       0          0

[1680 rows x 2 columns]

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Action'].plot(kind='hist', bins=20, title='Action')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Adventure'].plot(kind='hist', bins=20, title='Adventure')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='index', y='Action', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Action', y='Adventure', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Action']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Action')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Adventure']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Adventure')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_8['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Action'].plot(kind='line', figsize=(8, 4), title='Action')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Adventure'].plot(kind='line', figsize=(8, 4), title='Adventure')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
movie.loc[:, ['Action','Adventure']].sum()

Action       251
Adventure    135
dtype: int64

In [ ]:
# movie.drop(columns=['New genre'])

movie id                          movie title release date  Action  \
0            1                           Toy Story      1-Jan-95       0   
1            2                           GoldenEye      1-Jan-95       1   
2            3                          Four Rooms      1-Jan-95       0   
3            4                          Get Shorty      1-Jan-95       1   
4            5                             Copycat      1-Jan-95       0   
...        ...                                  ...          ...     ...   
1675      1678                          Mat' i syn      6-Feb-98       0   
1676      1679                           B. Monkey      6-Feb-98       0   
1677      1680                       Sliding Doors      1-Jan-98       0   
1678      1681                        You So Crazy      1-Jan-94       0   
1679      1682  Scream of Stone (Schrei aus Stein)      8-Mar-96       0   

      Adventure  Animation  Childrens  Comedy  Crime  Documentary  ...  \
0             0          1          1       1      0            0  ...   
1             1          0          0       0      0            0  ...   
2             0          0          0       0      0            0  ...   
3             0          0          0       1      0            0  ...   
4             0          0          0       0      1            0  ...   
...         ...        ...        ...     ...    ...          ...  ...   
1675          0          0          0       0      0            0  ...   
1676          0          0          0       0      0            0  ...   
1677          0          0          0       0      0            0  ...   
1678          0          0          0       1      0            0  ...   
1679          0          0          0       0      0            0  ...   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1675          0       0        0        0        0       0         0    0   
1676          0       0        0        0        1       0         1    0   
1677          0       0        0        0        1       0         0    0   
1678          0       0        0        0        0       0         0    0   
1679          0       0        0        0        0       0         0    0   

      Western  New-genre  
0           0          3  
1           0          3  
2           0          1  
3           0          3  
4           0          3  
...       ...        ...  
1675        0          1  
1676        0          2  
1677        0          2  
1678        0          1  
1679        0          1  

[1680 rows x 22 columns]

In [ ]:
movie[movie['New-genre']>1].shape

(849, 22)

In [ ]:
movie.columns

Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western', 'New-genre'],
      dtype='object')

# How many movies belong to a particular genre?

In [ ]:
movie.loc[:, genres].sum()

Action         251
Adventure      135
Animation       42
Childrens      122
Comedy         505
Crime          109
Documentary     50
Drama          725
Fantasy         22
Film-Noir       24
Horror          92
Musical         56
Mystery         61
Romance        247
Sci-Fi         101
Thriller       251
War             71
Western         27
dtype: int64

In [ ]:
movie.loc[:, genres].sum().sort_values(ascending=False)

Drama          725
Comedy         505
Action         251
Thriller       251
Romance        247
Adventure      135
Childrens      122
Crime          109
Sci-Fi         101
Horror          92
War             71
Mystery         61
Musical         56
Documentary     50
Animation       42
Western         27
Film-Noir       24
Fantasy         22
dtype: int64

In [ ]:
movie.loc[:, genres].sum().sort_values(ascending=False).count()

18

In [ ]:
# prompt:

# Number of movies per genre
movie_genre_count = movie[genres].sum(axis=0)

# Sort the genres by their movie count in descending order
sorted_movie_genres = movie_genre_count.sort_values(ascending=False)

# Print the number of movies per genre
print(sorted_movie_genres)


Drama          725
Comedy         505
Action         251
Thriller       251
Romance        247
Adventure      135
Childrens      122
Crime          109
Sci-Fi         101
Horror          92
War             71
Mystery         61
Musical         56
Documentary     50
Animation       42
Western         27
Film-Noir       24
Fantasy         22
dtype: int64


# Find the movies that have more than one genre?

# Insights


*   849 out of 1680 movies belong to more than one genre




In [ ]:
# Get all the rows more than 1 value in the column 'New-genre'
list_of_rows = movie['New-genre']>1
print(list_of_rows)

0        True
1        True
2       False
3        True
4        True
        ...  
1675    False
1676     True
1677     True
1678    False
1679    False
Name: New-genre, Length: 1680, dtype: bool


In [ ]:
# Get all movie data which belong to more than one genre
movies_more_than_one_genre = movie[list_of_rows]
movies_more_than_one_genre

#print(movie[movie['New-genre']>1])

#movie[movie['New-genre']>1]

movie id         movie title release date  Action  Adventure  Animation  \
0            1          Toy Story      1-Jan-95       0          0          1   
1            2          GoldenEye      1-Jan-95       1          1          0   
3            4         Get Shorty      1-Jan-95       1          0          0   
4            5            Copycat      1-Jan-95       0          0          0   
6            7     Twelve Monkeys      1-Jan-95       0          0          0   
...        ...                 ...          ...     ...        ...        ...   
1666      1669  MURDER and murder     20-Jun-97       0          0          0   
1667      1670            Tainted      1-Feb-98       0          0          0   
1670      1673             Mirage      1-Jan-95       1          0          0   
1676      1679          B. Monkey      6-Feb-98       0          0          0   
1677      1680      Sliding Doors      1-Jan-98       0          0          0   

      Childrens  Comedy  Crime  Documentary  ...     725      22      24  \
0             1       1      0            0  ...  Action  Action  Action   
1             0       0      0            0  ...  Action  Action  Action   
3             0       1      0            0  ...  Action  Action  Action   
4             0       0      1            0  ...  Action  Action  Action   
6             0       0      0            0  ...  Action  Action  Action   
...         ...     ...    ...          ...  ...     ...     ...     ...   
1666          0       0      1            0  ...  Action  Action  Action   
1667          0       1      0            0  ...  Action  Action  Action   
1670          0       0      0            0  ...  Action  Action  Action   
1676          0       0      0            0  ...  Action  Action  Action   
1677          0       0      0            0  ...  Action  Action  Action   

          92      56      61     247     101      71      27  
0     Action  Action  Action  Action  Action  Action  Action  
1     Action  Action  Action  Action  Action  Action  Action  
3     Action  Action  Action  Action  Action  Action  Action  
4     Action  Action  Action  Action  Action  Action  Action  
6     Action  Action  Action  Action  Action  Action  Action  
...      ...     ...     ...     ...     ...     ...     ...  
1666  Action  Action  Action  Action  Action  Action  Action  
1667  Action  Action  Action  Action  Action  Action  Action  
1670  Action  Action  Action  Action  Action  Action  Action  
1676  Action  Action  Action  Action  Action  Action  Action  
1677  Action  Action  Action  Action  Action  Action  Action  

[849 rows x 39 columns]

In [ ]:
movie[movie['New-genre']>1].shape

(849, 39)

# Find the genres that are most liked by the users?

Insigts:


*   Which genre has highest rating
*   Which genres have low rating



In [ ]:
ratings = pd.read_csv("drive/MyDrive/GreatLearning/data/ratings.csv")
print(ratings.shape)
ratings.head()
ratings.describe()
ratings.columns


(100000, 4)


Index(['user id', 'movie id', 'rating', 'timestamp'], dtype='object')

In [ ]:
ratings

user id  movie id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [ ]:
df_merge = movie.merge(ratings, on='movie id', how = 'inner')
df_merge

movie id                          movie title release date  Action  \
0             1                           Toy Story      1-Jan-95       0   
1             1                           Toy Story      1-Jan-95       0   
2             1                           Toy Story      1-Jan-95       0   
3             1                           Toy Story      1-Jan-95       0   
4             1                           Toy Story      1-Jan-95       0   
...         ...                                  ...          ...     ...   
99985      1678                          Mat' i syn      6-Feb-98       0   
99986      1679                           B. Monkey      6-Feb-98       0   
99987      1680                       Sliding Doors      1-Jan-98       0   
99988      1681                        You So Crazy      1-Jan-94       0   
99989      1682  Scream of Stone (Schrei aus Stein)      8-Mar-96       0   

       Adventure  Animation  Childrens  Comedy  Crime  Documentary  ...  \
0              0          1          1       1      0            0  ...   
1              0          1          1       1      0            0  ...   
2              0          1          1       1      0            0  ...   
3              0          1          1       1      0            0  ...   
4              0          1          1       1      0            0  ...   
...          ...        ...        ...     ...    ...          ...  ...   
99985          0          0          0       0      0            0  ...   
99986          0          0          0       0      0            0  ...   
99987          0          0          0       0      0            0  ...   
99988          0          0          0       1      0            0  ...   
99989          0          0          0       0      0            0  ...   

           92      56      61     247     101      71      27  user id  \
0      Action  Action  Action  Action  Action  Action  Action      308   
1      Action  Action  Action  Action  Action  Action  Action      287   
2      Action  Action  Action  Action  Action  Action  Action      148   
3      Action  Action  Action  Action  Action  Action  Action      280   
4      Action  Action  Action  Action  Action  Action  Action       66   
...       ...     ...     ...     ...     ...     ...     ...      ...   
99985  Action  Action  Action  Action  Action  Action  Action      863   
99986  Action  Action  Action  Action  Action  Action  Action      863   
99987  Action  Action  Action  Action  Action  Action  Action      863   
99988  Action  Action  Action  Action  Action  Action  Action      896   
99989  Action  Action  Action  Action  Action  Action  Action      916   

       rating  timestamp  
0           4  887736532  
1           5  875334088  
2           4  877019411  
3           4  891700426  
4           3  883601324  
...       ...        ...  
99985       1  889289570  
99986       3  889289491  
99987       2  889289570  
99988       3  887160722  
99989       3  880845755  

[99990 rows x 42 columns]

In [ ]:
# # ratings of individual
# rating = df_merge[df_merge['Action']==1].rating
# # mean of that rating for Action movie
# rating.mean()

for i in genres:
    print(i,':' , df_merge[df_merge[i]==1].rating.mean())

Action : 3.5298929892989297
Adventure : 3.503526503308369
Animation : 3.5766990291262135
Childrens : 3.3532442216652742
Comedy : 3.3940734781442745
Crime : 3.6322780881440098
Documentary : 3.6728232189973613
Drama : 3.6873793708484772
Fantasy : 3.2152366863905324
Film-Noir : 3.9215233698788228
Horror : 3.2903893172841827
Musical : 3.521396851029471
Mystery : 3.63813155386082
Romance : 3.621704948358255
Sci-Fi : 3.5607227022780834
Thriller : 3.5090069495245064
War : 3.815811874866993
Western : 3.6132686084142396


In [ ]:
# prompt:

# Merge the 'movies' and 'ratings' dataframes on the common column 'movieId'
#merged_df = pd.merge(movie, ratings, on='movieId')
merged_df = pd.merge(movie, ratings, on='movie id')

# Group the merged dataframe by 'genres' and calculate the average rating for each genre
average_ratings_by_genre = merged_df.groupby(genres)['rating'].mean()

# # Sort the average ratings in descending order
sorted_average_ratings = average_ratings_by_genre.sort_values(ascending=False)
sorted_average_ratings#
# # Print the sorted average ratings
#print(sorted_average_ratings)


Action  Adventure  Animation  Childrens  Comedy  Crime  Documentary  Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
0       0          1          0          1       0      0            0      0        0          0       0        0        0        0       1         0    0          4.491071
                                         0       0      0            0      0        0          0       0        0        0        0       0         0    0          4.430556
                   0          0          0       0      0            0      0        0          0       0        0        0        1       0         1    0          4.252577
                                                 1      0            0      0        1          0       0        0        0        0       0         0    0          4.250000
1       1          0          0          0       0      0            1      0        0          0       0        0        1        1       0  

# Few examples to understand the joins

In [ ]:
data = {'City': ['New York', 'Chicago', 'New York', 'Chicago', 'New York'],
        'Temperature': [10, 20, 15, 25, 12],
        'Humidity': [50, 60, 55, 65, 52]}

df = pd.DataFrame(data)
#print(df)
# Group by 'City' and calculate the mean temperature and humidity for each city
grouped = df.groupby('City').mean()

#print(grouped)

df.groupby('City')['Humidity'].mean()

City
Chicago     62.500000
New York    52.333333
Name: Humidity, dtype: float64

In [ ]:
product = pd.DataFrame({
    "Customer_id" : [1,2,3,4,5,6],
    "Product":['Oven', 'Oven', 'Oven', 'Television', 'Television', 'Television']
})

state = pd.DataFrame({
    "Customer_id" : [2,4,6,7,8],
    "State":['California', 'California', 'Texas', 'Las Vegas', 'Las Vegas']
})
print(product)
print(state)
prod_stat_merged = pd.merge(product, state, on='Customer_id')
print(prod_stat_merged)

prod_stat_merged_left = pd.merge(product, state, how = 'left')
print(prod_stat_merged_left)

prod_stat_merged_right = pd.merge(product, state, how = 'right')
print(prod_stat_merged_right)

prod_stat_merged_outer = pd.merge(product, state, how = 'outer')
print(prod_stat_merged_outer)


   Customer_id     Product
0            1        Oven
1            2        Oven
2            3        Oven
3            4  Television
4            5  Television
5            6  Television
   Customer_id       State
0            2  California
1            4  California
2            6       Texas
3            7   Las Vegas
4            8   Las Vegas
   Customer_id     Product       State
0            2        Oven  California
1            4  Television  California
2            6  Television       Texas
   Customer_id     Product       State
0            1        Oven         NaN
1            2        Oven  California
2            3        Oven         NaN
3            4  Television  California
4            5  Television         NaN
5            6  Television       Texas
   Customer_id     Product       State
0            2        Oven  California
1            4  Television  California
2            6  Television       Texas
3            7         NaN   Las Vegas
4            8         Na

# Find which movies have been most preferred by the users?

In [ ]:
user = pd.read_csv("drive/MyDrive/GreatLearning/data/user.csv")
print(user.shape)
user.head()
user.info()
user.describe()
user.columns
user

(943, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   user id     943 non-null    int64 
 1   age         943 non-null    int64 
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB


user id  age gender     occupation zip code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [ ]:
movie

movie id                          movie title release date  Action  \
0            1                           Toy Story      1-Jan-95       0   
1            2                           GoldenEye      1-Jan-95       1   
2            3                          Four Rooms      1-Jan-95       0   
3            4                          Get Shorty      1-Jan-95       1   
4            5                             Copycat      1-Jan-95       0   
...        ...                                  ...          ...     ...   
1675      1678                          Mat' i syn      6-Feb-98       0   
1676      1679                           B. Monkey      6-Feb-98       0   
1677      1680                       Sliding Doors      1-Jan-98       0   
1678      1681                        You So Crazy      1-Jan-94       0   
1679      1682  Scream of Stone (Schrei aus Stein)      8-Mar-96       0   

      Adventure  Animation  Childrens  Comedy  Crime  Documentary  ...  \
0             0          1          1       1      0            0  ...   
1             1          0          0       0      0            0  ...   
2             0          0          0       0      0            0  ...   
3             0          0          0       1      0            0  ...   
4             0          0          0       0      1            0  ...   
...         ...        ...        ...     ...    ...          ...  ...   
1675          0          0          0       0      0            0  ...   
1676          0          0          0       0      0            0  ...   
1677          0          0          0       0      0            0  ...   
1678          0          0          0       1      0            0  ...   
1679          0          0          0       0      0            0  ...   

         725      22      24      92      56      61     247     101      71  \
0     Action  Action  Action  Action  Action  Action  Action  Action  Action   
1     Action  Action  Action  Action  Action  Action  Action  Action  Action   
2     Action  Action  Action  Action  Action  Action  Action  Action  Action   
3     Action  Action  Action  Action  Action  Action  Action  Action  Action   
4     Action  Action  Action  Action  Action  Action  Action  Action  Action   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1675  Action  Action  Action  Action  Action  Action  Action  Action  Action   
1676  Action  Action  Action  Action  Action  Action  Action  Action  Action   
1677  Action  Action  Action  Action  Action  Action  Action  Action  Action   
1678  Action  Action  Action  Action  Action  Action  Action  Action  Action   
1679  Action  Action  Action  Action  Action  Action  Action  Action  Action   

          27  
0     Action  
1     Action  
2     Action  
3     Action  
4     Action  
...      ...  
1675  Action  
1676  Action  
1677  Action  
1678  Action  
1679  Action  

[1680 rows x 39 columns]

In [ ]:
df_merge

movie id                          movie title release date  Action  \
0             1                           Toy Story      1-Jan-95       1   
1             1                           Toy Story      1-Jan-95       1   
2             1                           Toy Story      1-Jan-95       1   
3             1                           Toy Story      1-Jan-95       1   
4             1                           Toy Story      1-Jan-95       1   
...         ...                                  ...          ...     ...   
99985      1678                          Mat' i syn      6-Feb-98       1   
99986      1679                           B. Monkey      6-Feb-98       1   
99987      1680                       Sliding Doors      1-Jan-98       1   
99988      1681                        You So Crazy      1-Jan-94       1   
99989      1682  Scream of Stone (Schrei aus Stein)      8-Mar-96       1   

       Adventure  Animation  Childrens  Comedy  Crime  Documentary  ...  \
0              0          1          1       1      0            0  ...   
1              0          1          1       1      0            0  ...   
2              0          1          1       1      0            0  ...   
3              0          1          1       1      0            0  ...   
4              0          1          1       1      0            0  ...   
...          ...        ...        ...     ...    ...          ...  ...   
99985          0          0          0       0      0            0  ...   
99986          0          0          0       0      0            0  ...   
99987          0          0          0       0      0            0  ...   
99988          0          0          0       1      0            0  ...   
99989          0          0          0       0      0            0  ...   

           92      56      61     247     101      71      27  user id  \
0      Action  Action  Action  Action  Action  Action  Action      308   
1      Action  Action  Action  Action  Action  Action  Action      287   
2      Action  Action  Action  Action  Action  Action  Action      148   
3      Action  Action  Action  Action  Action  Action  Action      280   
4      Action  Action  Action  Action  Action  Action  Action       66   
...       ...     ...     ...     ...     ...     ...     ...      ...   
99985  Action  Action  Action  Action  Action  Action  Action      863   
99986  Action  Action  Action  Action  Action  Action  Action      863   
99987  Action  Action  Action  Action  Action  Action  Action      863   
99988  Action  Action  Action  Action  Action  Action  Action      896   
99989  Action  Action  Action  Action  Action  Action  Action      916   

       rating  timestamp  
0           4  887736532  
1           5  875334088  
2           4  877019411  
3           4  891700426  
4           3  883601324  
...       ...        ...  
99985       1  889289570  
99986       3  889289491  
99987       2  889289570  
99988       3  887160722  
99989       3  880845755  

[99990 rows x 42 columns]

In [ ]:
df_merge.groupby(['movie title'])['rating'].mean()

movie title
'Til There Was You                 2.333333
1-900                              2.600000
101 Dalmatians                     2.908257
12 Angry Men                       4.344000
187                                3.024390
                                     ...   
Young Guns                         3.207921
Young Guns II                      2.772727
Young Poisoner's Handbook, The     3.341463
Zeus and Roxanne                   2.166667
Á köldum klaka (Cold Fever)        3.000000
Name: rating, Length: 1657, dtype: float64

In [ ]:
df_merge.groupby(['movie title'])['rating'].mean().reset_index()

movie title    rating
0                 'Til There Was You   2.333333
1                              1-900   2.600000
2                     101 Dalmatians   2.908257
3                       12 Angry Men   4.344000
4                                 187  3.024390
...                               ...       ...
1652                      Young Guns   3.207921
1653                   Young Guns II   2.772727
1654  Young Poisoner's Handbook, The   3.341463
1655                Zeus and Roxanne   2.166667
1656     Á köldum klaka (Cold Fever)   3.000000

[1657 rows x 2 columns]

In [ ]:
avg_rating = df_merge.groupby(['movie title'])['rating'].mean().reset_index()
avg_rating

movie title    rating
0                 'Til There Was You   2.333333
1                              1-900   2.600000
2                     101 Dalmatians   2.908257
3                       12 Angry Men   4.344000
4                                 187  3.024390
...                               ...       ...
1652                      Young Guns   3.207921
1653                   Young Guns II   2.772727
1654  Young Poisoner's Handbook, The   3.341463
1655                Zeus and Roxanne   2.166667
1656     Á köldum klaka (Cold Fever)   3.000000

[1657 rows x 2 columns]

In [ ]:
#rename
# avg_rating.rename(columns={'rating':'Avg_rating'},inplace=True)
# avg_rating.head()
avg_rating.rename(columns= {'rating':'Avg_rating'})
avg_rating.sort_values(by='Avg_rating',ascending=False)

movie title  Avg_rating
631                       Great Day in Harlem, A          5.0
1170                                 Prefontaine          5.0
1354                      Someone Else's America          5.0
461   Entertaining Angels: The Dorothy Day Story          5.0
942          Marlene Dietrich: Shadow and Light (         5.0
...                                           ...         ...
111                                    Babyfever          1.0
834                               Lashou shentan          1.0
1307                            Shadows (Cienie)          1.0
1304       Shadow of Angels (Schatten der Engel)          1.0
1168                                    Power 98          1.0

[1657 rows x 2 columns]

In [ ]:
avg_rating[avg_rating['Avg_rating']==5]

movie title  Avg_rating
30                                 Aiqing wansui          5.0
461   Entertaining Angels: The Dorothy Day Story          5.0
631                       Great Day in Harlem, A          5.0
942          Marlene Dietrich: Shadow and Light (         5.0
1170                                 Prefontaine          5.0
1270               Saint of Fort Washington, The          5.0
1274                          Santa with Muscles          5.0
1354                      Someone Else's America          5.0
1382                                    Star Kid          5.0
1466                     They Made Me a Criminal          5.0

## Find which movies are rated most of the times?

In [ ]:
df_merge.head(20)

movie title  Rating_counts
1393                    Star Wars             583
332                       Contact             509
497                         Fargo             508
1232           Return of the Jedi             507
858                     Liar Liar             485
...                            ...            ...
1085  Object of My Affection, The               1
1088                Office Killer               1
1109    Other Voices, Other Rooms               1
1123            Paris Was a Woman               1
1656  Á köldum klaka (Cold Fever)               1

[1657 rows x 2 columns]

# Count how many times movies are rated

In [ ]:
movie_count = df_merge.groupby(['movie title'])['rating'].count().reset_index()
movie_count

movie title  rating
0                 'Til There Was You        9
1                              1-900        5
2                     101 Dalmatians      109
3                       12 Angry Men      125
4                                 187      41
...                               ...     ...
1652                      Young Guns      101
1653                   Young Guns II       44
1654  Young Poisoner's Handbook, The       41
1655                Zeus and Roxanne        6
1656     Á köldum klaka (Cold Fever)        1

[1657 rows x 2 columns]

# Rename the column 'rating' to 'Ratings_counts'

In [ ]:
movie_count.rename(columns={'rating':'Rating_counts'},inplace=True)
movie_count.head()

movie title  Rating_counts
0  'Til There Was You               9
1               1-900               5
2      101 Dalmatians             109
3        12 Angry Men             125
4                  187             41

# Sort the movies by rated times in descending order

In [ ]:
movie_count.sort_values(ascending=False, by= 'Rating_counts')

movie title  Rating_counts
1393                    Star Wars             583
332                       Contact             509
497                         Fargo             508
1232           Return of the Jedi             507
858                     Liar Liar             485
...                            ...            ...
1085  Object of My Affection, The               1
1088                Office Killer               1
1109    Other Voices, Other Rooms               1
1123            Paris Was a Woman               1
1656  Á köldum klaka (Cold Fever)               1

[1657 rows x 2 columns]

# Movies rated more than 100 times

In [ ]:
movie_100 = movie_count[movie_count['Rating_counts']>100] #this will subset the dataset 'movie_count' as per the specified condition
movie_100

movie title  Rating_counts
2                            101 Dalmatians             109
3                              12 Angry Men             125
7                     2001: A Space Odyssey             259
15                           Absolute Power             127
16                               Abyss, The             151
...                                      ...            ...
1627  Willy Wonka and the Chocolate Factory             326
1638                      Wizard of Oz, The             246
1646                    Wrong Trousers, The             118
1651                     Young Frankenstein             200
1652                             Young Guns             101

[334 rows x 2 columns]

# Merge Average ratings with movies rated more than 100 times

In [ ]:
df_top= avg_rating.merge(movie_100, on = 'movie title', how = 'inner')
df_top

movie title  Avg_rating  Rating_counts
0                           101 Dalmatians     2.908257            109
1                             12 Angry Men     4.344000            125
2                    2001: A Space Odyssey     3.969112            259
3                           Absolute Power     3.370079            127
4                               Abyss, The     3.589404            151
..                                      ...         ...            ...
329  Willy Wonka and the Chocolate Factory     3.631902            326
330                      Wizard of Oz, The     4.077236            246
331                    Wrong Trousers, The     4.466102            118
332                     Young Frankenstein     3.945000            200
333                             Young Guns     3.207921            101

[334 rows x 3 columns]

# Display top 25 movies on the basis of average rating

In [ ]:
df_top.sort_values(ascending=False, by='Avg_rating').head(25) #display top 25 movies on the basis of average rating

movie title  Avg_rating  \
63                                     Close Shave, A     4.491071   
260                                  Schindler's List     4.466443   
331                               Wrong Trousers, The     4.466102   
54                                         Casablanca     4.456790   
269                         Shawshank Redemption, The     4.445230   
248                                       Rear Window     4.387560   
319                               Usual Suspects, The     4.385768   
291                                         Star Wars     4.358491   
1                                        12 Angry Men     4.344000   
59                                       Citizen Kane     4.292929   
305                             To Kill a Mockingbird     4.292237   
222                   One Flew Over the Cuckoo's Nest     4.291667   
272                         Silence of the Lambs, The     4.289744   
218                                North by Northwest     4.284916   
131                                    Godfather, The     4.283293   
264                                    Secrets & Lies     4.265432   
135                                 Good Will Hunting     4.262626   
189                         Manchurian Candidate, The     4.259542   
91   Dr. Strangelove or: How I Learned to Stop Worr...    4.252577   
243                           Raiders of the Lost Ark     4.252381   
320                                           Vertigo     4.251397   
304                                           Titanic     4.245714   
176                                Lawrence of Arabia     4.231214   
188                               Maltese Falcon, The     4.210145   
98                           Empire Strikes Back, The     4.204360   

     Rating_counts  
63             112  
260            298  
331            118  
54             243  
269            283  
248            209  
319            267  
291            583  
1              125  
59             198  
305            219  
222            264  
272            390  
218            179  
131            413  
264            162  
135            198  
189            131  
91             194  
243            420  
320            179  
304            350  
176            173  
188            138  
98             367

# **Sort and display top 25 movies on the basis of rating counts**

In [ ]:
df_top.sort_values(ascending=False, by='Rating_counts').head(25) #d

movie title  Avg_rating  Rating_counts
291                           Star Wars     4.358491            583
69                              Contact     3.803536            509
107                               Fargo     4.155512            508
251                  Return of the Jedi     4.007890            507
178                           Liar Liar     3.156701            485
99                 English Patient, The     3.656965            481
261                              Scream     3.441423            478
309                           Toy Story     3.878319            452
8                         Air Force One     3.631090            431
159              Independence Day (ID4)     3.438228            429
243             Raiders of the Lost Ark     4.252381            420
131                      Godfather, The     4.283293            413
240                        Pulp Fiction     4.060914            394
314                      Twelve Monkeys     3.798469            392
272           Silence of the Lambs, The     4.289744            390
167                       Jerry Maguire     3.710938            384
55                          Chasing Amy     3.839050            379
254                           Rock, The     3.693122            378
98             Empire Strikes Back, The     4.204360            367
287            Star Trek: First Contact     3.660274            365
304                             Titanic     4.245714            350
25                   Back to the Future     3.834286            350
199                 Mission: Impossible     3.313953            344
119                       Fugitive, The     4.044643            336
160  Indiana Jones and the Last Crusade     3.930514            331

# Insights
There are 334 movies in total which have received ratings more than 100 times

*   As per the average rating, Close Shave, A* has maximum average rating with a rating count of 112*
*   As per the rating counts, Star Wars* has received maximum number counts with an average rating of 4.35*
*   There are few movies which have least rating counts like Paris Was a Woman ,Á köldum klaka (Cold Fever)

# *****************************************

# Extract some relationship between demographic details of the users and ratings for the movies?

**Merge all datasets**

In [ ]:
df_merge_all = df_merge.merge(user, on = 'user id', how = 'inner')
df_merge_all.head()

movie id      movie title release date  Action  Adventure  Animation  \
0         1       Toy Story      1-Jan-95       1          0          1   
1         4      Get Shorty      1-Jan-95       1          0          0   
2         5         Copycat      1-Jan-95       1          0          0   
3         7  Twelve Monkeys      1-Jan-95       1          0          0   
4         8            Babe      1-Jan-95       1          0          0   

   Childrens  Comedy  Crime  Documentary  ...     101      71      27  \
0          1       1      0            0  ...  Action  Action  Action   
1          0       1      0            0  ...  Action  Action  Action   
2          0       0      1            0  ...  Action  Action  Action   
3          0       0      0            0  ...  Action  Action  Action   
4          1       1      0            0  ...  Action  Action  Action   

   user id  rating  timestamp  age  gender  occupation  zip code  
0      308       4  887736532   60       M     retired     95076  
1      308       5  887737890   60       M     retired     95076  
2      308       4  887739608   60       M     retired     95076  
3      308       4  887738847   60       M     retired     95076  
4      308       5  887736696   60       M     retired     95076  

[5 rows x 46 columns]

**Get the proportion of males and females users extracted from User dataset**

In [ ]:
user['gender'].value_counts(normalize=True)

gender
M    0.710498
F    0.289502
Name: proportion, dtype: float64

**Grouping the dataset on 'gender' column and taking the average of ratings**

In [ ]:
df_merge_all.groupby('gender').rating.mean() #grouping the dataset on 'gender' column and taking the average of ratings

gender
F    3.531510
M    3.529333
Name: rating, dtype: float64

**Grouping the dataset on 'occupation' column and taking the average of ratings.**

In [ ]:
df_merge_all.groupby('occupation').rating.mean().sort_values(ascending= False) #grouping the dataset on 'occupation' column and taking the average of ratings.

occupation
none             3.777778
lawyer           3.735316
doctor           3.688889
educator         3.670692
artist           3.653380
administrator    3.635646
scientist        3.611273
salesman         3.582944
programmer       3.568205
librarian        3.560781
other            3.552335
engineer         3.541473
technician       3.532097
student          3.515167
marketing        3.485641
retired          3.466750
entertainment    3.440783
writer           3.376152
executive        3.349794
homemaker        3.301003
healthcare       2.896220
Name: rating, dtype: float64

# Insights


*   Around 71% of users are Males while only 29% users are females
The average rating given by Males and Females is almost equal with a value of around 3.53
*   Users who are not working have given highest ratings as compared to users who are working professionals
*   Healthcare workers have given lowest ratings on an average
*   The low ratings from the healthcare sector is majorly driven by female workers
*   Only male doctors have given ratings. No female doctors have given ratings as per the observations